package view.ordre;

import control.Controller;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import view.OrdreGUI;

/**
 *
 * @author TheToiletpaper
 */
public class BestillingsOrdreGUI extends javax.swing.JPanel {
    
    OrdreGUI ordreGUI;
    private Calendar dato;
    private Calendar deliveryDato;
    private int year;
    private int month;
    private int day;
    private int yearDelivery;
    private int monthDelivery;
    private int dayDelivery;
    
    public BestillingsOrdreGUI(OrdreGUI org) {
        this.ordreGUI = org;
        dato = Calendar.getInstance();
        year = dato.get(Calendar.YEAR);
        month = dato.get(Calendar.MONTH) + 1; // Regner fra 0 - 11. Derfor +1
        day = dato.get(Calendar.DAY_OF_MONTH);
        deliveryDato = Calendar.getInstance();
        deliveryDato.add(Calendar.DAY_OF_MONTH, 7);
        yearDelivery = deliveryDato.get(Calendar.YEAR);
        monthDelivery = deliveryDato.get(Calendar.MONTH) + 1;
        dayDelivery = deliveryDato.get(Calendar.DAY_OF_MONTH);
        
        initComponents();
        
        jTextField5.setText(day + " / " + month + " / " + year);
        jTextField3.setText(dayDelivery + " / " + monthDelivery + " / " + yearDelivery);
    }
    
    public void opdaterPris() {
        double totalPris = 0;
        double inskriptionsPris = 0;
        double rabat = 0;
        ArrayList<ProduktTilListe> ptl = ordreGUI.getProduktGUI().getListeAfProdukterTilOrdre();
        for (ProduktTilListe produktTilListe : ptl) {
            totalPris = totalPris + produktTilListe.getSalgsPris();
        }
        ArrayList<TilfojelseTilListe> tfl = ordreGUI.getTilfoejelseGUI().getListeAfTilfoejelserTilOrdre();
        for (TilfojelseTilListe tilfojelseTilListe : tfl) {
            totalPris = totalPris + tilfojelseTilListe.getPris();
        }
        if (!jTextField1.getText().isEmpty()) {
            inskriptionsPris = Double.parseDouble(jTextField1.getText());
        }
        totalPris = totalPris + inskriptionsPris;
        if (!jTextField4.getText().isEmpty()) {
            rabat = Double.parseDouble(jTextField4.getText());
            totalPris = totalPris - rabat;
        }
        jTextField2.setText(totalPris + "");
        double prisMedMoms = totalPris + ((totalPris / 100) * 25);
        jTextField9.setText(prisMedMoms + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(100, 100, 100));
        setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inskription:");
        add(jLabel1);
        jLabel1.setBounds(100, 130, 120, 16);

        jTextField2.setText("0");
        add(jTextField2);
        jTextField2.setBounds(200, 380, 100, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pris u/ moms:");
        add(jLabel2);
        jLabel2.setBounds(40, 380, 100, 16);

        jTextField1.setText("0");
        add(jTextField1);
        jTextField1.setBounds(200, 320, 100, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Antal bogstaver/timer:");
        add(jLabel4);
        jLabel4.setBounds(40, 320, 150, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 150, 244, 140);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Skrifttype:");
        add(jLabel3);
        jLabel3.setBounds(330, 60, 90, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Skriftstørrelse:");
        add(jLabel6);
        jLabel6.setBounds(330, 20, 120, 16);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3);
        jScrollPane3.setBounds(330, 150, 244, 140);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bemærkninger:");
        add(jLabel7);
        jLabel7.setBounds(390, 130, 120, 16);

        jButton1.setText("Opret ordre!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(590, 410, 140, 29);
        add(jTextField3);
        jTextField3.setBounds(450, 410, 110, 20);

        jLabel8.setBackground(new java.awt.Color(100, 100, 100));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bestillingsdato:");
        add(jLabel8);
        jLabel8.setBounds(330, 380, 120, 20);

        jLabel10.setBackground(new java.awt.Color(100, 100, 100));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Leveringsdato:");
        add(jLabel10);
        jLabel10.setBounds(330, 410, 120, 16);

        jLabel11.setBackground(new java.awt.Color(100, 100, 100));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Rabat:");
        add(jLabel11);
        jLabel11.setBounds(40, 350, 100, 16);

        jTextField4.setText("0");
        add(jTextField4);
        jTextField4.setBounds(200, 350, 100, 20);

        jLabel12.setBackground(new java.awt.Color(100, 100, 100));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Skriftstil:");
        add(jLabel12);
        jLabel12.setBounds(330, 100, 110, 16);

        jLabel16.setBackground(new java.awt.Color(100, 100, 100));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Miljøafgift 2,5 %");
        add(jLabel16);
        jLabel16.setBounds(175, 450, 120, 16);
        add(jTextField5);
        jTextField5.setBounds(450, 380, 110, 20);

        jTextField6.setText("0");
        add(jTextField6);
        jTextField6.setBounds(460, 20, 120, 20);

        jTextField7.setText("0");
        add(jTextField7);
        jTextField7.setBounds(460, 58, 120, 20);

        jTextField8.setText("0");
        add(jTextField8);
        jTextField8.setBounds(460, 98, 120, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pris m/ moms:");
        add(jLabel5);
        jLabel5.setBounds(40, 410, 100, 16);

        jTextField9.setText("0");
        add(jTextField9);
        jTextField9.setBounds(200, 410, 100, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        String str = jTextArea1.getText();
        str = str.replace(" ", "");
        str = str.replace(".", "");
        int length = str.length();
        jTextField1.setText(length + "");
        opdaterPris();
    }//GEN-LAST:event_jTextArea1KeyReleased
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Controller controller = new Controller();
        Date bestilling = dato.getTime();
        Date levering = deliveryDato.getTime();
        String skriftType = jTextField7.getText();
        int skrifStoerrelse = Integer.parseInt(jTextField6.getText());
        int skriftStil = Integer.parseInt(jTextField8.getText());
        String inskriptionsLinje = jTextArea1.getText();
        String bemaerkninger = jTextArea3.getText();
        double totalPris = Double.parseDouble(jTextField2.getText());
        double rabat = Double.parseDouble(jTextField4.getText());
        int kundeTlf = ordreGUI.getKundeGUI().getKundeTelefonNr();
        
        ArrayList<ProduktTilListe> ptl = ordreGUI.getProduktGUI().getListeAfProdukterTilOrdre();
        ArrayList<TilfojelseTilListe> tfl = ordreGUI.getTilfoejelseGUI().getListeAfTilfoejelserTilOrdre();
        
        controller.connGemOrdreIDatabase(bestilling, levering, skriftType, skrifStoerrelse, skriftStil, inskriptionsLinje, bemaerkninger, totalPris, rabat, kundeTlf, ptl, tfl);

    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
