package view.ordre;

import control.Controller;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import view.OrdreGUI;

/**
 *
 * @author Dan-Philip Christensen
 */
public class ProduktGUI extends javax.swing.JPanel {

    OrdreGUI ordreGUI;
    ArrayList<ProduktTilListe> listeAfProdukter;
    ArrayList<ProduktTilListe> listeAfProdukterTilOrdre;

    public ProduktGUI(OrdreGUI org) {
        ordreGUI = org;
        listeAfProdukter = new ArrayList<>();
        listeAfProdukterTilOrdre = new ArrayList<>();
        initComponents();
        
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{
                    "Gravsten", "Bronze Dekorationer", "Granitplaner",
                    "Fuglebad", "Granitvaser"}));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produktListe = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        soegeKnap = new javax.swing.JButton();
        indsaetProduktIOrdreKnap = new javax.swing.JButton();
        fortsaetKnap = new javax.swing.JButton();

        setBackground(new java.awt.Color(100, 100, 100));

<<<<<<< HEAD
=======
        jLabel1.setText(" Produktnavn:");

>>>>>>> a97dbf69963c103e96a8b97144608a25a58076f2
        produktListe.setBackground(new java.awt.Color(238, 238, 238));
        produktListe.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        produktListe.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setForeground(new java.awt.Color(128, 128, 128));
        produktListe.setViewportView(jPanel1);

        soegeKnap.setText("Søg");
        soegeKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soegeKnapActionPerformed(evt);
            }
        });

        indsaetProduktIOrdreKnap.setText("Indsæt valgte produkt i ordre");
        indsaetProduktIOrdreKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indsaetProduktIOrdreKnapActionPerformed(evt);
            }
        });

        fortsaetKnap.setText("Spring over");
        fortsaetKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fortsaetKnapActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(produktListe)
                    .add(layout.createSequentialGroup()
<<<<<<< HEAD
                        .add(10, 10, 10)
                        .add(jLabel2)
                        .add(143, 143, 143)
                        .add(jLabel3)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(99, 99, 99)
                                .add(soegeKnap)
                                .add(18, 18, 18)
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(indsaetProduktIOrdreKnap)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 524, Short.MAX_VALUE)
                                .add(fortsaetKnap))
                            .add(layout.createSequentialGroup()
                                .add(148, 148, 148)
                                .add(jLabel4)
                                .add(83, 83, 83)
                                .add(jLabel5)
                                .add(104, 104, 104)
                                .add(jLabel6)
                                .add(79, 79, 79)
                                .add(jLabel7)
                                .add(101, 101, 101)
                                .add(jLabel8)
                                .add(0, 0, Short.MAX_VALUE)))))
=======
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(4, 4, 4)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(soegeKnap)
                        .add(18, 18, 18)
                        .add(indsaetProduktIOrdreKnap)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 598, Short.MAX_VALUE)
                        .add(fortsaetKnap)))
>>>>>>> a97dbf69963c103e96a8b97144608a25a58076f2
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(soegeKnap)
                    .add(indsaetProduktIOrdreKnap)
                    .add(fortsaetKnap)
<<<<<<< HEAD
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jLabel7)
                    .add(jLabel8))
                .add(10, 10, 10)
=======
                    .add(jLabel1))
                .add(30, 30, 30)
>>>>>>> a97dbf69963c103e96a8b97144608a25a58076f2
                .add(produktListe, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<ProduktTilListe> getListeAfProdukterTilOrdre() {
        return listeAfProdukterTilOrdre;
    }

    public void foejTilListeAfProdukter(int produktNr, String produktNavn,
            String produktType, int antalILager, double maalX, double maalY, double salgsPris) {
        ProduktTilListe ptl = new ProduktTilListe(produktNr, produktNavn,
                produktType, produktNr, maalX, maalY, salgsPris);
        listeAfProdukter.add(ptl);
    }

    private void soegeKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soegeKnapActionPerformed
        listeAfProdukter.clear();
        Controller controller = new Controller();
        controller.connSoegEfterProdukt(jComboBox1.getSelectedItem().toString(), this);

        jPanel1.removeAll();
        for (int i = 0; i < listeAfProdukter.size(); i++) {
            jPanel1.add(listeAfProdukter.get(i));
        }
        jPanel1.setPreferredSize(new Dimension(1272, jPanel1.getComponentCount() * 45));
        produktListe.revalidate();
        produktListe.repaint();
    }//GEN-LAST:event_soegeKnapActionPerformed

    private void fortsaetKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fortsaetKnapActionPerformed
        ordreGUI.skiftOrdrePanel("TilfoejelseGUI");
        ordreGUI.getTilføjelser().setBackground(new Color(150,150,150));
        ordreGUI.getProdukt().setBackground(new Color(240,240,240));
        ordreGUI.getBtilføjelser().setBackground(new Color(150,150,150));
        
    }//GEN-LAST:event_fortsaetKnapActionPerformed

    private void indsaetProduktIOrdreKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indsaetProduktIOrdreKnapActionPerformed
        for (int i = 0; i < listeAfProdukter.size(); i++) {
            if (listeAfProdukter.get(i).isChosen()) {
                listeAfProdukterTilOrdre.add(listeAfProdukter.get(i));
            }
        }
        if (listeAfProdukterTilOrdre.isEmpty()) {
            fortsaetKnap.setText("Spring over");
        }else {
            fortsaetKnap.setText("Videre");
        }
    }//GEN-LAST:event_indsaetProduktIOrdreKnapActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fortsaetKnap;
    private javax.swing.JButton indsaetProduktIOrdreKnap;
<<<<<<< HEAD
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
=======
    private javax.swing.JLabel jLabel1;
>>>>>>> a97dbf69963c103e96a8b97144608a25a58076f2
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane produktListe;
    private javax.swing.JButton soegeKnap;
    // End of variables declaration//GEN-END:variables
}
