package view.ordre;

import control.Controller;
import java.awt.Dimension;
import java.util.ArrayList;
import view.OrdreGUI;

/**
 *
 * @author Dan-Philip Christensen
 */
public class ProduktGUI extends javax.swing.JPanel {

    OrdreGUI ordreGUI;
    ArrayList<ProduktTilListe> listeAfProdukter;
    ArrayList<ProduktTilListe> listeAfProdukterTilOrdre;

    public ProduktGUI(OrdreGUI org) {
        ordreGUI = org;
        listeAfProdukter = new ArrayList<>();
        listeAfProdukterTilOrdre = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        produktListe = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        soegeKnap = new javax.swing.JButton();
        indsaetProduktIOrdreKnap = new javax.swing.JButton();
        fortsaetKnap = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(100, 100, 100));

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText(" Produktnavn:");

        produktListe.setBackground(new java.awt.Color(238, 238, 238));
        produktListe.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        produktListe.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));
        jPanel1.setForeground(new java.awt.Color(128, 128, 128));
        produktListe.setViewportView(jPanel1);

        soegeKnap.setText("Søg");
        soegeKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soegeKnapActionPerformed(evt);
            }
        });

        indsaetProduktIOrdreKnap.setText("Indsæt valgte produkt i ordre");
        indsaetProduktIOrdreKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indsaetProduktIOrdreKnapActionPerformed(evt);
            }
        });

        fortsaetKnap.setText("Spring over");
        fortsaetKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fortsaetKnapActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("VareID:");

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Navn:");

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Type:");

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Antal:");

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Længde:");

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Bredde:");

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Pris:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(produktListe)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jLabel2)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(4, 4, 4)
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(61, 61, 61)
                                .add(jLabel3)))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(soegeKnap)
                                .add(18, 18, 18)
                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel4)
                                .add(47, 47, 47)))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(indsaetProduktIOrdreKnap)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(fortsaetKnap))
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jLabel5)
                                .add(104, 104, 104)
                                .add(jLabel6)
                                .add(79, 79, 79)
                                .add(jLabel7)
                                .add(101, 101, 101)
                                .add(jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 363, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(soegeKnap)
                    .add(indsaetProduktIOrdreKnap)
                    .add(fortsaetKnap)
                    .add(jLabel1)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jLabel7)
                    .add(jLabel8))
                .add(10, 10, 10)
                .add(produktListe, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<ProduktTilListe> getListeAfProdukterTilOrdre() {
        return listeAfProdukterTilOrdre;
    }

    public void foejTilListeAfProdukter(int produktNr, String produktNavn,
            String produktType, int antalILager, double maalX, double maalY, double salgsPris) {
        ProduktTilListe ptl = new ProduktTilListe(produktNr, produktNavn,
                produktType, produktNr, maalX, maalY, salgsPris);
        listeAfProdukter.add(ptl);
    }

    private void soegeKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soegeKnapActionPerformed
        listeAfProdukter.clear();
        
        Controller controller = new Controller();
        controller.connSoegEfterProdukt(jTextField1.getText(), this);

        jPanel1.removeAll();
        for (int i = 0; i < listeAfProdukter.size(); i++) {
            jPanel1.add(listeAfProdukter.get(i));
        }
        jPanel1.setPreferredSize(new Dimension(1272, jPanel1.getComponentCount() * 45));
        produktListe.revalidate();
        produktListe.repaint();
    }//GEN-LAST:event_soegeKnapActionPerformed

    private void fortsaetKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fortsaetKnapActionPerformed
        ordreGUI.skiftOrdrePanel("TilfoejelseGUI");
    }//GEN-LAST:event_fortsaetKnapActionPerformed

    private void indsaetProduktIOrdreKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indsaetProduktIOrdreKnapActionPerformed
        for (int i = 0; i < listeAfProdukter.size(); i++) {
            if (listeAfProdukter.get(i).isChosen()) {
                listeAfProdukterTilOrdre.add(listeAfProdukter.get(i));
            }
        }
        if (listeAfProdukterTilOrdre.isEmpty()) {
            fortsaetKnap.setText("Spring over");
        }else {
            fortsaetKnap.setText("Videre");
        }
    }//GEN-LAST:event_indsaetProduktIOrdreKnapActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fortsaetKnap;
    private javax.swing.JButton indsaetProduktIOrdreKnap;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane produktListe;
    private javax.swing.JButton soegeKnap;
    // End of variables declaration//GEN-END:variables
}
