package view.ordre;

import java.awt.Color;

/**
 *
 * @author Dan-Philip-N
 */
public class TilfojelseTilListe extends javax.swing.JPanel {

    private boolean chosen;
    
    public TilfojelseTilListe(int tilfoejelsesID, String tilfoejelsesType, double tilfoejelsesPris) {
        chosen = false;
        initComponents();
        this.tilfoejelsesID.setText(tilfoejelsesID + "");
        this.tilfoejelsesNavn.setText(tilfoejelsesType);
        this.salgsPris.setText(tilfoejelsesPris + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tilfoejelsesID = new javax.swing.JLabel();
        tilfoejelsesNavn = new javax.swing.JLabel();
        salgsPris = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tilfoejelsesID.setText("Tilføjelses Nr.");

        tilfoejelsesNavn.setText("Tilføjelsestype");

        salgsPris.setText("Pris");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tilfoejelsesID, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tilfoejelsesNavn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salgsPris, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tilfoejelsesID)
                    .addComponent(tilfoejelsesNavn)
                    .addComponent(salgsPris))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean isChosen() {
        return chosen;
    }

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (!chosen) {
            chosen = true;
            this.setBackground(Color.CYAN);
        } else {
            chosen = false;
            this.setBackground(new Color(128, 128, 128));
        }
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel salgsPris;
    private javax.swing.JLabel tilfoejelsesID;
    private javax.swing.JLabel tilfoejelsesNavn;
    // End of variables declaration//GEN-END:variables
}
