/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ordre;

import control.Controller;
import java.awt.Dimension;
import java.util.ArrayList;
import view.OrdreGUI;

/**
 *
 * @author Dan-Philip Christensen
 */
public class TilfoejelseGUI extends javax.swing.JPanel {

    OrdreGUI ordreGUI;
    ArrayList<TilfojelseTilListe> listeAfTilfoejelser;
    ArrayList<TilfojelseTilListe> listeAfTilfoejelserTilOrdre;

    public TilfoejelseGUI(OrdreGUI org) {
        listeAfTilfoejelser = new ArrayList<>();
        listeAfTilfoejelserTilOrdre = new ArrayList<>();
        ordreGUI = org;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        soegeKnap = new javax.swing.JButton();
        indsaetProduktIOrdreKnap = new javax.swing.JButton();
        produktListe = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        fortsaetKnap = new javax.swing.JButton();

        setBackground(new java.awt.Color(100, 100, 100));

        jLabel1.setText("Tilføjelsestype:");

        soegeKnap.setText("Søg");
        soegeKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soegeKnapActionPerformed(evt);
            }
        });

        indsaetProduktIOrdreKnap.setText("Indsæt valgte tilføjelse i ordre");
        indsaetProduktIOrdreKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indsaetProduktIOrdreKnapActionPerformed(evt);
            }
        });

        produktListe.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        produktListe.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        produktListe.setViewportView(jPanel1);

        fortsaetKnap.setText("Spring over");
        fortsaetKnap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fortsaetKnapActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(produktListe)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(4, 4, 4)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(soegeKnap)
                        .add(18, 18, 18)
                        .add(indsaetProduktIOrdreKnap)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 599, Short.MAX_VALUE)
                        .add(fortsaetKnap)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(soegeKnap)
                    .add(indsaetProduktIOrdreKnap)
                    .add(fortsaetKnap)
                    .add(jLabel1))
                .add(30, 30, 30)
                .add(produktListe, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void foejTilListeAfTilfoejelser(int tilfoejelsesID, String tilfoejelsesType, double tilfoejelsesPris) {
        TilfojelseTilListe ttl = new TilfojelseTilListe(tilfoejelsesID, tilfoejelsesType, tilfoejelsesPris);
        listeAfTilfoejelser.add(ttl);
    }

    private void soegeKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soegeKnapActionPerformed
        listeAfTilfoejelser.clear();

        Controller controller = new Controller();
        controller.connSoegEfterTilfoejelse(jTextField1.getText(), this);

        jPanel1.removeAll();
        for (int i = 0; i < listeAfTilfoejelser.size(); i++) {
            jPanel1.add(listeAfTilfoejelser.get(i));
        }
        jPanel1.setPreferredSize(new Dimension(1272, jPanel1.getComponentCount() * 45));
        produktListe.revalidate();
        produktListe.repaint();
    }//GEN-LAST:event_soegeKnapActionPerformed

    private void fortsaetKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fortsaetKnapActionPerformed
        if (ordreGUI.isKirkegaardsOrdre()) {
            ordreGUI.skiftOrdrePanel("KirkegaardGUI");
        } else {
            ordreGUI.skiftOrdrePanel("BestillingsOrdreGUI");
        }
    }//GEN-LAST:event_fortsaetKnapActionPerformed

    private void indsaetProduktIOrdreKnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indsaetProduktIOrdreKnapActionPerformed
        for (int i = 0; i < listeAfTilfoejelser.size(); i++) {
            if (listeAfTilfoejelser.get(i).isChosen()) {
                listeAfTilfoejelserTilOrdre.add(listeAfTilfoejelser.get(i));
            }
        }
        if (listeAfTilfoejelserTilOrdre.isEmpty()) {
            fortsaetKnap.setText("Spring over");
        } else {
            fortsaetKnap.setText("Videre");
        }
    }//GEN-LAST:event_indsaetProduktIOrdreKnapActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fortsaetKnap;
    private javax.swing.JButton indsaetProduktIOrdreKnap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JScrollPane produktListe;
    private javax.swing.JButton soegeKnap;
    // End of variables declaration//GEN-END:variables

    public ArrayList<TilfojelseTilListe> getListeAfTilfoejelserTilOrdre() {
        return listeAfTilfoejelserTilOrdre;
    }
}
