/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.faktura;

/**
 *
 * @author Jackson
 */
public class FakturaForm extends javax.swing.JPanel {

    /**
     * Creates new form FakturaForm
     */
    public FakturaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billedeLabel = new javax.swing.JLabel();
        infoEtLabel = new javax.swing.JLabel();
        infoToLabel = new javax.swing.JLabel();
        infoTreLabel = new javax.swing.JLabel();
        infoFireLabel = new javax.swing.JLabel();
        infoFemLabel = new javax.swing.JLabel();
        infoSeksLabel = new javax.swing.JLabel();
        infoSyvLabel = new javax.swing.JLabel();
        infoOtteLabel = new javax.swing.JLabel();
        infoNiLabel = new javax.swing.JLabel();
        faktureresTilLabelNoChange = new javax.swing.JLabel();
        datoLabelNoChange = new javax.swing.JLabel();
        fakturaNrLabelNoChange = new javax.swing.JLabel();
        datoLabelTilOrdrebekræftelse = new javax.swing.JLabel();
        fakturaNrLabel = new javax.swing.JLabel();
        kundeNavnLabel = new javax.swing.JLabel();
        kundeAdresseLabel = new javax.swing.JLabel();
        kundePostOgByLabel = new javax.swing.JLabel();
        antalLabelNoChange = new javax.swing.JLabel();
        vareLabelNoChange = new javax.swing.JLabel();
        prisLabelNoChange = new javax.swing.JLabel();
        antaEtLabel = new javax.swing.JLabel();
        antaToLabel = new javax.swing.JLabel();
        antaTreLabel = new javax.swing.JLabel();
        antaFireLabel = new javax.swing.JLabel();
        antaFemLabel = new javax.swing.JLabel();
        antaSeksLabel = new javax.swing.JLabel();
        antaSyvLabel = new javax.swing.JLabel();
        miljøAfgiftAntalLabelNoChange = new javax.swing.JLabel();
        vareEtLabel = new javax.swing.JLabel();
        vareToLabel = new javax.swing.JLabel();
        varetreLabel = new javax.swing.JLabel();
        vareFireLabel = new javax.swing.JLabel();
        vareFemLabel = new javax.swing.JLabel();
        vareSeksLabel = new javax.swing.JLabel();
        vareSyvLabel = new javax.swing.JLabel();
        miljøAfgiftVareLavbelNoChange = new javax.swing.JLabel();
        prisEtLabel = new javax.swing.JLabel();
        prisToLabel = new javax.swing.JLabel();
        prisTreLabel = new javax.swing.JLabel();
        prisFireLabel = new javax.swing.JLabel();
        prisFemLabel = new javax.swing.JLabel();
        prisSeksLabel = new javax.swing.JLabel();
        prisSyvLabel = new javax.swing.JLabel();
        prisMiljøafgift = new javax.swing.JLabel();
        subtotalLabelNoChange = new javax.swing.JLabel();
        momsLabelNoChange = new javax.swing.JLabel();
        salgsmomsLabelNoChange = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        momsLabel = new javax.swing.JLabel();
        salgsmomsLabel = new javax.swing.JLabel();
        vedrørendeLabelNoChange = new javax.swing.JLabel();
        ordrenummerLabelNoChange = new javax.swing.JLabel();
        ordrenummerLabel = new javax.swing.JLabel();
        vedrLabelNoChange = new javax.swing.JLabel();
        vedrLabel = new javax.swing.JLabel();
        enhedsprisLabelNoChange = new javax.swing.JLabel();
        enhedsprisLabelEt = new javax.swing.JLabel();
        enhedsprisLabelTo = new javax.swing.JLabel();
        enhedsprisLabelTre = new javax.swing.JLabel();
        enhedsprisLabelFem = new javax.swing.JLabel();
        enhedsprisLabelSeks = new javax.swing.JLabel();
        enhedsprisLabelSyv = new javax.swing.JLabel();
        enhedsprisLabelOtteNoChange = new javax.swing.JLabel();
        enhedsprisLabelFire = new javax.swing.JLabel();
        fakturaLabelNoChange = new javax.swing.JLabel();
        iAltLabelNoChange = new javax.swing.JLabel();
        iAltLabel = new javax.swing.JLabel();
        betalingsBetingelserLabelNoChange = new javax.swing.JLabel();
        betalingsBetingelser = new javax.swing.JLabel();
        betalingsInfoNoChange = new javax.swing.JLabel();
        betalingsInfoToNoChange = new javax.swing.JLabel();
        betalingaInfoTreNoChange = new javax.swing.JLabel();
        betalingsInfoFireNoChange = new javax.swing.JLabel();

        billedeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bejerholm Faktura.png"))); // NOI18N

        infoEtLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        infoEtLabel.setText("Bejerholms Stenhuggeri v/René Bejerholm Poulsen");

        infoToLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoToLabel.setText("Fægangen 8, 4220 Korsør, Tlf. 58 35 00 04");

        infoTreLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoTreLabel.setText("Nørre Allé, 440 Kalundborg, Tlf. 42 76 00 04");

        infoFireLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoFireLabel.setText("Fax 58 35 00 33");

        infoFemLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoFemLabel.setText("bejerholm.stenhuggeri@gmail.com");

        infoSeksLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoSeksLabel.setText("www.bejerholms-stenhuggeri.dk");

        infoSyvLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoSyvLabel.setText("CVR-NR: 32931898");

        infoOtteLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        infoOtteLabel.setText("Sydbank - Reg. nr. 6821");

        infoNiLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        infoNiLabel.setText("Konto 1021974");

        faktureresTilLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        faktureresTilLabelNoChange.setText("Faktureres til:");

        datoLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        datoLabelNoChange.setText("DATO:");

        fakturaNrLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fakturaNrLabelNoChange.setText("FAKTURANR:");

        datoLabelTilOrdrebekræftelse.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        datoLabelTilOrdrebekræftelse.setPreferredSize(new java.awt.Dimension(100, 16));

        fakturaNrLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fakturaNrLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        kundeNavnLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kundeNavnLabel.setText(" ");
        kundeNavnLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kundeNavnLabel.setPreferredSize(new java.awt.Dimension(250, 16));

        kundeAdresseLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kundeAdresseLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kundeAdresseLabel.setPreferredSize(new java.awt.Dimension(250, 16));

        kundePostOgByLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kundePostOgByLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kundePostOgByLabel.setPreferredSize(new java.awt.Dimension(250, 16));

        antalLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        antalLabelNoChange.setText("Antal                 ");
        antalLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        vareLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        vareLabelNoChange.setText("BESKRIVELSE");
        vareLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        prisLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        prisLabelNoChange.setText("BELØB");
        prisLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        antaEtLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaEtLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaEtLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        antaToLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaToLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaToLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        antaTreLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaTreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaTreLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        antaFireLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaFireLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaFireLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        antaFemLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaFemLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaFemLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        antaSeksLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaSeksLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaSeksLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        antaSyvLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaSyvLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaSyvLabel.setPreferredSize(new java.awt.Dimension(115, 16));

        miljøAfgiftAntalLabelNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        miljøAfgiftAntalLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        miljøAfgiftAntalLabelNoChange.setPreferredSize(new java.awt.Dimension(115, 16));

        vareEtLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareEtLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareEtLabel.setPreferredSize(new java.awt.Dimension(319, 16));

        vareToLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareToLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareToLabel.setPreferredSize(new java.awt.Dimension(319, 16));

        varetreLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        varetreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        varetreLabel.setPreferredSize(new java.awt.Dimension(319, 16));

        vareFireLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareFireLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareFireLabel.setPreferredSize(new java.awt.Dimension(319, 16));

        vareFemLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareFemLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareFemLabel.setPreferredSize(new java.awt.Dimension(319, 16));

        vareSeksLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareSeksLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareSeksLabel.setPreferredSize(new java.awt.Dimension(319, 16));

        vareSyvLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareSyvLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareSyvLabel.setPreferredSize(new java.awt.Dimension(319, 16));

        miljøAfgiftVareLavbelNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        miljøAfgiftVareLavbelNoChange.setText("Miljøafgift (2,5%)");
        miljøAfgiftVareLavbelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        miljøAfgiftVareLavbelNoChange.setPreferredSize(new java.awt.Dimension(319, 16));

        prisEtLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisEtLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisEtLabel.setPreferredSize(new java.awt.Dimension(125, 16));

        prisToLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisToLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisToLabel.setPreferredSize(new java.awt.Dimension(125, 16));

        prisTreLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisTreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisTreLabel.setPreferredSize(new java.awt.Dimension(125, 16));

        prisFireLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisFireLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisFireLabel.setPreferredSize(new java.awt.Dimension(125, 16));

        prisFemLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisFemLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisFemLabel.setPreferredSize(new java.awt.Dimension(125, 16));

        prisSeksLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisSeksLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisSeksLabel.setPreferredSize(new java.awt.Dimension(125, 16));

        prisSyvLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisSyvLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisSyvLabel.setPreferredSize(new java.awt.Dimension(125, 16));

        prisMiljøafgift.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisMiljøafgift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisMiljøafgift.setPreferredSize(new java.awt.Dimension(125, 16));

        subtotalLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        subtotalLabelNoChange.setText("SUBTOTAL:");

        momsLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        momsLabelNoChange.setText("MOMS:");

        salgsmomsLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        salgsmomsLabelNoChange.setText("SALGSMOMS:");

        subtotalLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        subtotalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subtotalLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        momsLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        momsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        momsLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        salgsmomsLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        salgsmomsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        salgsmomsLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        vedrørendeLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        vedrørendeLabelNoChange.setText("Vedrørende:");

        ordrenummerLabelNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ordrenummerLabelNoChange.setText("Ordrenummer:");

        ordrenummerLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ordrenummerLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ordrenummerLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        vedrLabelNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vedrLabelNoChange.setText("Vedr.");

        vedrLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vedrLabel.setText("    ");
        vedrLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vedrLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        enhedsprisLabelNoChange.setText("ENHEDSPRIS");
        enhedsprisLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelNoChange.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelEt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enhedsprisLabelEt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelEt.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelTo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enhedsprisLabelTo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelTo.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelTre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enhedsprisLabelTre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelTre.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelFem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enhedsprisLabelFem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelFem.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelSeks.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enhedsprisLabelSeks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelSeks.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelSyv.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enhedsprisLabelSyv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelSyv.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelOtteNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enhedsprisLabelOtteNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelOtteNoChange.setPreferredSize(new java.awt.Dimension(100, 16));

        enhedsprisLabelFire.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        enhedsprisLabelFire.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enhedsprisLabelFire.setPreferredSize(new java.awt.Dimension(100, 16));

        fakturaLabelNoChange.setFont(new java.awt.Font("Arial Black", 0, 28)); // NOI18N
        fakturaLabelNoChange.setForeground(new java.awt.Color(51, 153, 255));
        fakturaLabelNoChange.setText("FAKTURA");

        iAltLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        iAltLabelNoChange.setText("I ALT");

        iAltLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        iAltLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iAltLabel.setPreferredSize(new java.awt.Dimension(100, 16));

        betalingsBetingelserLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        betalingsBetingelserLabelNoChange.setText("Betalingsbetingelser: ");

        betalingsBetingelser.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        betalingsBetingelser.setPreferredSize(new java.awt.Dimension(100, 16));

        betalingsInfoNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        betalingsInfoNoChange.setText("Sydbank: 6821 - 1021974");

        betalingsInfoToNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        betalingsInfoToNoChange.setText("\"Ordrenummer og navn\" bedes anført ved bankoverførsel");

        betalingaInfoTreNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        betalingaInfoTreNoChange.setText("Hvis der er spørgsmål til denne faktura, bedes De venligst kontakte");

        betalingsInfoFireNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        betalingsInfoFireNoChange.setText("René Bejerholm Poulsen, 58 35 00 04, bejerholm@bejerholms-stenhuggeri.dk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(faktureresTilLabelNoChange)
                            .addComponent(kundePostOgByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kundeAdresseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kundeNavnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vedrørendeLabelNoChange)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ordrenummerLabelNoChange)
                                    .addComponent(vedrLabelNoChange))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ordrenummerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vedrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fakturaLabelNoChange)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(antaEtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(vareEtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(enhedsprisLabelEt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(antaSeksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(vareSeksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(antaSyvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(vareSyvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(betalingaInfoTreNoChange)
                                                    .addComponent(betalingsInfoNoChange)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(betalingsBetingelserLabelNoChange)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(betalingsBetingelser, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(betalingsInfoToNoChange)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(miljøAfgiftAntalLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(miljøAfgiftVareLavbelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(enhedsprisLabelSyv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(enhedsprisLabelOtteNoChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(enhedsprisLabelSeks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(antaFemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(vareFemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(enhedsprisLabelFem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(antaFireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(antaTreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(antaToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(antalLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(vareLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(enhedsprisLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addGap(5, 5, 5)
                                                            .addComponent(vareToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(varetreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(vareFireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(enhedsprisLabelTre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(enhedsprisLabelFire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(enhedsprisLabelTo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(prisFemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(prisSeksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(prisSyvLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(prisMiljøafgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prisLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prisToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prisTreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prisFireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prisEtLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(datoLabelNoChange)
                                                .addComponent(fakturaNrLabelNoChange))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fakturaNrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(datoLabelTilOrdrebekræftelse, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(9, 9, 9))
                                        .addComponent(billedeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(infoEtLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(infoToLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(infoTreLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(194, 194, 194)
                                                .addComponent(infoFireLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(infoFemLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(127, 127, 127)
                                                .addComponent(infoSeksLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(177, 177, 177)
                                                .addComponent(infoSyvLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(147, 147, 147)
                                                .addComponent(infoOtteLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(194, 194, 194)
                                                .addComponent(infoNiLabel))))
                                    .addGap(1, 1, 1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(iAltLabelNoChange)
                                .addGap(10, 10, 10)
                                .addComponent(iAltLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(subtotalLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(momsLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(salgsmomsLabelNoChange))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(momsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(subtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(salgsmomsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(betalingsInfoFireNoChange)))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(fakturaLabelNoChange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(faktureresTilLabelNoChange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kundeNavnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(kundeAdresseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kundePostOgByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(vedrørendeLabelNoChange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ordrenummerLabelNoChange)
                                    .addComponent(ordrenummerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vedrLabelNoChange)
                                    .addComponent(vedrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(billedeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(infoEtLabel)
                        .addGap(6, 6, 6)
                        .addComponent(infoToLabel)
                        .addGap(6, 6, 6)
                        .addComponent(infoTreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(infoFireLabel)
                        .addGap(6, 6, 6)
                        .addComponent(infoFemLabel)
                        .addGap(6, 6, 6)
                        .addComponent(infoSeksLabel)
                        .addGap(6, 6, 6)
                        .addComponent(infoSyvLabel)
                        .addGap(6, 6, 6)
                        .addComponent(infoOtteLabel)
                        .addGap(6, 6, 6)
                        .addComponent(infoNiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datoLabelNoChange)
                                .addGap(8, 8, 8)
                                .addComponent(fakturaNrLabelNoChange))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(datoLabelTilOrdrebekræftelse, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fakturaNrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(antalLabelNoChange)
                            .addComponent(vareLabelNoChange)
                            .addComponent(enhedsprisLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enhedsprisLabelEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(enhedsprisLabelTre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(antaEtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(antaToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vareToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(enhedsprisLabelTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(vareEtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(antaTreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(antaFireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vareFireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(enhedsprisLabelFire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(varetreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vareFemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enhedsprisLabelFem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(antaFemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vareSeksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(antaSeksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vareSyvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(antaSyvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(miljøAfgiftAntalLabelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(miljøAfgiftVareLavbelNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enhedsprisLabelSeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enhedsprisLabelSyv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(enhedsprisLabelOtteNoChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prisLabelNoChange)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prisFireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(prisEtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(prisToLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(prisTreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prisFemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(prisSyvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(prisMiljøafgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(prisSeksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(momsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(salgsmomsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(iAltLabelNoChange)
                                    .addComponent(iAltLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subtotalLabelNoChange)
                                .addGap(6, 6, 6)
                                .addComponent(momsLabelNoChange)
                                .addGap(6, 6, 6)
                                .addComponent(salgsmomsLabelNoChange))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(betalingsBetingelserLabelNoChange)
                                    .addComponent(betalingsBetingelser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(betalingsInfoNoChange)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(betalingsInfoToNoChange)
                                .addGap(18, 18, 18)
                                .addComponent(betalingaInfoTreNoChange)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(betalingsInfoFireNoChange)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel antaEtLabel;
    private javax.swing.JLabel antaFemLabel;
    private javax.swing.JLabel antaFireLabel;
    private javax.swing.JLabel antaSeksLabel;
    private javax.swing.JLabel antaSyvLabel;
    private javax.swing.JLabel antaToLabel;
    private javax.swing.JLabel antaTreLabel;
    private javax.swing.JLabel antalLabelNoChange;
    private javax.swing.JLabel betalingaInfoTreNoChange;
    private javax.swing.JLabel betalingsBetingelser;
    private javax.swing.JLabel betalingsBetingelserLabelNoChange;
    private javax.swing.JLabel betalingsInfoFireNoChange;
    private javax.swing.JLabel betalingsInfoNoChange;
    private javax.swing.JLabel betalingsInfoToNoChange;
    private javax.swing.JLabel billedeLabel;
    private javax.swing.JLabel datoLabelNoChange;
    private javax.swing.JLabel datoLabelTilOrdrebekræftelse;
    private javax.swing.JLabel enhedsprisLabelEt;
    private javax.swing.JLabel enhedsprisLabelFem;
    private javax.swing.JLabel enhedsprisLabelFire;
    private javax.swing.JLabel enhedsprisLabelNoChange;
    private javax.swing.JLabel enhedsprisLabelOtteNoChange;
    private javax.swing.JLabel enhedsprisLabelSeks;
    private javax.swing.JLabel enhedsprisLabelSyv;
    private javax.swing.JLabel enhedsprisLabelTo;
    private javax.swing.JLabel enhedsprisLabelTre;
    private javax.swing.JLabel fakturaLabelNoChange;
    private javax.swing.JLabel fakturaNrLabel;
    private javax.swing.JLabel fakturaNrLabelNoChange;
    private javax.swing.JLabel faktureresTilLabelNoChange;
    private javax.swing.JLabel iAltLabel;
    private javax.swing.JLabel iAltLabelNoChange;
    private javax.swing.JLabel infoEtLabel;
    private javax.swing.JLabel infoFemLabel;
    private javax.swing.JLabel infoFireLabel;
    private javax.swing.JLabel infoNiLabel;
    private javax.swing.JLabel infoOtteLabel;
    private javax.swing.JLabel infoSeksLabel;
    private javax.swing.JLabel infoSyvLabel;
    private javax.swing.JLabel infoToLabel;
    private javax.swing.JLabel infoTreLabel;
    private javax.swing.JLabel kundeAdresseLabel;
    private javax.swing.JLabel kundeNavnLabel;
    private javax.swing.JLabel kundePostOgByLabel;
    private javax.swing.JLabel miljøAfgiftAntalLabelNoChange;
    private javax.swing.JLabel miljøAfgiftVareLavbelNoChange;
    private javax.swing.JLabel momsLabel;
    private javax.swing.JLabel momsLabelNoChange;
    private javax.swing.JLabel ordrenummerLabel;
    private javax.swing.JLabel ordrenummerLabelNoChange;
    private javax.swing.JLabel prisEtLabel;
    private javax.swing.JLabel prisFemLabel;
    private javax.swing.JLabel prisFireLabel;
    private javax.swing.JLabel prisLabelNoChange;
    private javax.swing.JLabel prisMiljøafgift;
    private javax.swing.JLabel prisSeksLabel;
    private javax.swing.JLabel prisSyvLabel;
    private javax.swing.JLabel prisToLabel;
    private javax.swing.JLabel prisTreLabel;
    private javax.swing.JLabel salgsmomsLabel;
    private javax.swing.JLabel salgsmomsLabelNoChange;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel subtotalLabelNoChange;
    private javax.swing.JLabel vareEtLabel;
    private javax.swing.JLabel vareFemLabel;
    private javax.swing.JLabel vareFireLabel;
    private javax.swing.JLabel vareLabelNoChange;
    private javax.swing.JLabel vareSeksLabel;
    private javax.swing.JLabel vareSyvLabel;
    private javax.swing.JLabel vareToLabel;
    private javax.swing.JLabel varetreLabel;
    private javax.swing.JLabel vedrLabel;
    private javax.swing.JLabel vedrLabelNoChange;
    private javax.swing.JLabel vedrørendeLabelNoChange;
    // End of variables declaration//GEN-END:variables
}
