/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.faktura;

/**
 *
 * @author Jackson
 */
public class OrdreForm extends javax.swing.JPanel {

    /**
     * Creates new form OrdreForm
     */
    public OrdreForm() {
        initComponents();
        bemærkningerTextArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billedeLabel = new javax.swing.JLabel();
        infoEtLabel = new javax.swing.JLabel();
        infoToLabel = new javax.swing.JLabel();
        infoTreLabel = new javax.swing.JLabel();
        infoFireLabel = new javax.swing.JLabel();
        infoFemLabel = new javax.swing.JLabel();
        infoSeksLabel = new javax.swing.JLabel();
        infoSyvLabel = new javax.swing.JLabel();
        infoOtteLabel = new javax.swing.JLabel();
        infoNiLabel = new javax.swing.JLabel();
        KundeInformationLabelNoChange = new javax.swing.JLabel();
        ordrebekræftelseLabelNoChange = new javax.swing.JLabel();
        datoLabelNoChange = new javax.swing.JLabel();
        telefonLabelNoChange = new javax.swing.JLabel();
        ordreNrLabelNoChange = new javax.swing.JLabel();
        datoLabelTilOrdrebekræftelse = new javax.swing.JLabel();
        telefonLabelTilOrdrebekræftelse = new javax.swing.JLabel();
        ordreNrLabelTilOrdrebekræftelse = new javax.swing.JLabel();
        nyStenNrLabelNoChange = new javax.swing.JLabel();
        tilfoejelseLabelNoChange = new javax.swing.JLabel();
        kisteUrneLabelNoChange = new javax.swing.JLabel();
        afhDatoLabelNoChange = new javax.swing.JLabel();
        levDatoLabelNoChange = new javax.swing.JLabel();
        kirkegaardLabelNoChange = new javax.swing.JLabel();
        afdelingLabelNoChange = new javax.swing.JLabel();
        raekkeOgNrLabelNoChange = new javax.swing.JLabel();
        kundeNavnLabel = new javax.swing.JLabel();
        kundeAdresseLabel = new javax.swing.JLabel();
        kundePostOgByLabel = new javax.swing.JLabel();
        nyStenNrLabel = new javax.swing.JLabel();
        tilfoejelseLabel = new javax.swing.JLabel();
        kisteUrneLabel = new javax.swing.JLabel();
        afhDatoLabel = new javax.swing.JLabel();
        levDatoLabel = new javax.swing.JLabel();
        kirkegaardLabel = new javax.swing.JLabel();
        afdelingLabel = new javax.swing.JLabel();
        raekkeNrLabel = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        inskriptionFørsteLinie = new javax.swing.JLabel();
        inskriptionAndenLinie = new javax.swing.JLabel();
        inskriptionTredjeLinie = new javax.swing.JLabel();
        inskriptionFjerdeLinie = new javax.swing.JLabel();
        inskriptionFemteLinie = new javax.swing.JLabel();
        pladsTilLabelNoChange = new javax.swing.JLabel();
        antalNavneLabel = new javax.swing.JLabel();
        navneLabelNoChange = new javax.swing.JLabel();
        skrifttypeLabelNoChange = new javax.swing.JLabel();
        skriftTypeLabel = new javax.swing.JLabel();
        antalLabelNoChange = new javax.swing.JLabel();
        vareLabelNoChange = new javax.swing.JLabel();
        prisLabelNoChange = new javax.swing.JLabel();
        antaEtLabel = new javax.swing.JLabel();
        antaToLabel = new javax.swing.JLabel();
        antaTreLabel = new javax.swing.JLabel();
        antaFireLabel = new javax.swing.JLabel();
        antaFemLabel = new javax.swing.JLabel();
        antaSeksLabel = new javax.swing.JLabel();
        antaSyvLabel = new javax.swing.JLabel();
        miljøAfgiftAntalLabelNoChange = new javax.swing.JLabel();
        vareEtLabel = new javax.swing.JLabel();
        vareToLabel = new javax.swing.JLabel();
        varetreLabel = new javax.swing.JLabel();
        vareFireLabel = new javax.swing.JLabel();
        vareFemLabel = new javax.swing.JLabel();
        vareSeksLabel = new javax.swing.JLabel();
        vareSyvLabel = new javax.swing.JLabel();
        miljøAfgiftVareLavbelNoChange = new javax.swing.JLabel();
        prisEtLabel = new javax.swing.JLabel();
        prisToLabel = new javax.swing.JLabel();
        prisTreLabel = new javax.swing.JLabel();
        prisFireLabel = new javax.swing.JLabel();
        prisFemLabel = new javax.swing.JLabel();
        prisSeksLabel = new javax.swing.JLabel();
        prisSyvLabel = new javax.swing.JLabel();
        prisMiljøafgift = new javax.swing.JLabel();
        samletPrisUMomsLabelNoChange = new javax.swing.JLabel();
        momsLabelNoChange = new javax.swing.JLabel();
        totalPrisLabelNoChange = new javax.swing.JLabel();
        samletPrisUMomsLabel = new javax.swing.JLabel();
        momsLabel = new javax.swing.JLabel();
        totalPrisLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bemærkningerTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        billedeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bejerholm Faktura.png"))); // NOI18N
        add(billedeLabel);
        billedeLabel.setBounds(10, 19, 217, 162);

        infoEtLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        infoEtLabel.setText("Bejerholms Stenhuggeri v/René Bejerholm Poulsen");
        add(infoEtLabel);
        infoEtLabel.setBounds(314, 19, 271, 13);

        infoToLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoToLabel.setText("Fægangen 8, 4220 Korsør, Tlf. 58 35 00 04");
        add(infoToLabel);
        infoToLabel.setBounds(381, 38, 204, 13);

        infoTreLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoTreLabel.setText("Nørre Allé, 440 Kalundborg, Tlf. 42 76 00 04");
        add(infoTreLabel);
        infoTreLabel.setBounds(373, 57, 212, 10);

        infoFireLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoFireLabel.setText("Fax 58 35 00 33");
        add(infoFireLabel);
        infoFireLabel.setBounds(508, 76, 77, 13);

        infoFemLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoFemLabel.setText("bejerholm.stenhuggeri@gmail.com");
        add(infoFemLabel);
        infoFemLabel.setBounds(426, 95, 159, 13);

        infoSeksLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoSeksLabel.setText("www.bejerholms-stenhuggeri.dk");
        add(infoSeksLabel);
        infoSeksLabel.setBounds(441, 114, 144, 13);

        infoSyvLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        infoSyvLabel.setText("CVR-NR: 32931898");
        add(infoSyvLabel);
        infoSyvLabel.setBounds(491, 133, 94, 13);

        infoOtteLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        infoOtteLabel.setText("Sydbank - Reg. nr. 6821");
        add(infoOtteLabel);
        infoOtteLabel.setBounds(461, 152, 124, 14);

        infoNiLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        infoNiLabel.setText("Konto 1021974");
        add(infoNiLabel);
        infoNiLabel.setBounds(508, 172, 77, 14);

        KundeInformationLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        KundeInformationLabelNoChange.setText("Kundeinformation:");
        add(KundeInformationLabelNoChange);
        KundeInformationLabelNoChange.setBounds(10, 196, 102, 14);

        ordrebekræftelseLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        ordrebekræftelseLabelNoChange.setForeground(new java.awt.Color(255, 0, 0));
        ordrebekræftelseLabelNoChange.setText("Ordrebekræftelse:");
        add(ordrebekræftelseLabelNoChange);
        ordrebekræftelseLabelNoChange.setBounds(373, 192, 125, 19);

        datoLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        datoLabelNoChange.setText("Dato:");
        add(datoLabelNoChange);
        datoLabelNoChange.setBounds(380, 220, 30, 14);

        telefonLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        telefonLabelNoChange.setText("Telefon:");
        add(telefonLabelNoChange);
        telefonLabelNoChange.setBounds(380, 240, 45, 14);

        ordreNrLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ordreNrLabelNoChange.setText("Ordrenr:");
        add(ordreNrLabelNoChange);
        ordreNrLabelNoChange.setBounds(380, 260, 48, 14);

        datoLabelTilOrdrebekræftelse.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        datoLabelTilOrdrebekræftelse.setPreferredSize(new java.awt.Dimension(100, 16));
        add(datoLabelTilOrdrebekræftelse);
        datoLabelTilOrdrebekræftelse.setBounds(420, 220, 167, 20);

        telefonLabelTilOrdrebekræftelse.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        telefonLabelTilOrdrebekræftelse.setPreferredSize(new java.awt.Dimension(100, 16));
        add(telefonLabelTilOrdrebekræftelse);
        telefonLabelTilOrdrebekræftelse.setBounds(430, 240, 150, 16);

        ordreNrLabelTilOrdrebekræftelse.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ordreNrLabelTilOrdrebekræftelse.setPreferredSize(new java.awt.Dimension(100, 16));
        add(ordreNrLabelTilOrdrebekræftelse);
        ordreNrLabelTilOrdrebekræftelse.setBounds(430, 260, 150, 16);

        nyStenNrLabelNoChange.setText("Ny sten (nr.)     ");
        nyStenNrLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(nyStenNrLabelNoChange);
        nyStenNrLabelNoChange.setBounds(10, 299, 79, 16);

        tilfoejelseLabelNoChange.setText("Tilføjelse            ");
        tilfoejelseLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(tilfoejelseLabelNoChange);
        tilfoejelseLabelNoChange.setBounds(10, 326, 80, 16);

        kisteUrneLabelNoChange.setText("Kiste / Urne       ");
        kisteUrneLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(kisteUrneLabelNoChange);
        kisteUrneLabelNoChange.setBounds(10, 353, 79, 16);

        afhDatoLabelNoChange.setText("Afh. dato     ");
        afhDatoLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(afhDatoLabelNoChange);
        afhDatoLabelNoChange.setBounds(183, 299, 63, 16);

        levDatoLabelNoChange.setText("Lev. dato     ");
        levDatoLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(levDatoLabelNoChange);
        levDatoLabelNoChange.setBounds(183, 326, 63, 16);

        kirkegaardLabelNoChange.setText("Kirkegård:         ");
        kirkegaardLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(kirkegaardLabelNoChange);
        kirkegaardLabelNoChange.setBounds(373, 299, 78, 16);

        afdelingLabelNoChange.setText("Afdeling:           ");
        afdelingLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(afdelingLabelNoChange);
        afdelingLabelNoChange.setBounds(373, 326, 78, 16);

        raekkeOgNrLabelNoChange.setText("Række + Nr.:   ");
        raekkeOgNrLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(raekkeOgNrLabelNoChange);
        raekkeOgNrLabelNoChange.setBounds(373, 353, 77, 16);

        kundeNavnLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kundeNavnLabel.setText(" ");
        kundeNavnLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kundeNavnLabel.setPreferredSize(new java.awt.Dimension(250, 16));
        add(kundeNavnLabel);
        kundeNavnLabel.setBounds(10, 217, 310, 16);

        kundeAdresseLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kundeAdresseLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kundeAdresseLabel.setPreferredSize(new java.awt.Dimension(250, 16));
        add(kundeAdresseLabel);
        kundeAdresseLabel.setBounds(10, 240, 310, 16);

        kundePostOgByLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kundePostOgByLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kundePostOgByLabel.setPreferredSize(new java.awt.Dimension(250, 16));
        add(kundePostOgByLabel);
        kundePostOgByLabel.setBounds(10, 260, 310, 16);

        nyStenNrLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(nyStenNrLabel);
        nyStenNrLabel.setBounds(95, 301, 80, 16);

        tilfoejelseLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(tilfoejelseLabel);
        tilfoejelseLabel.setBounds(96, 327, 80, 16);

        kisteUrneLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(kisteUrneLabel);
        kisteUrneLabel.setBounds(95, 354, 80, 16);

        afhDatoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(afhDatoLabel);
        afhDatoLabel.setBounds(252, 300, 110, 16);

        levDatoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(levDatoLabel);
        levDatoLabel.setBounds(252, 327, 110, 16);

        kirkegaardLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(kirkegaardLabel);
        kirkegaardLabel.setBounds(457, 300, 110, 16);

        afdelingLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(afdelingLabel);
        afdelingLabel.setBounds(457, 327, 110, 16);

        raekkeNrLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(raekkeNrLabel);
        raekkeNrLabel.setBounds(456, 354, 110, 16);

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel38.setText("Inskription");
        add(jLabel38);
        jLabel38.setBounds(242, 387, 70, 14);

        inskriptionFørsteLinie.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inskriptionFørsteLinie.setText("jLabel39");
        add(inskriptionFørsteLinie);
        inskriptionFørsteLinie.setBounds(242, 419, 54, 19);

        inskriptionAndenLinie.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inskriptionAndenLinie.setText("jLabel40");
        add(inskriptionAndenLinie);
        inskriptionAndenLinie.setBounds(242, 439, 54, 19);

        inskriptionTredjeLinie.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inskriptionTredjeLinie.setText("jLabel41");
        add(inskriptionTredjeLinie);
        inskriptionTredjeLinie.setBounds(242, 459, 54, 19);

        inskriptionFjerdeLinie.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inskriptionFjerdeLinie.setText("jLabel42");
        add(inskriptionFjerdeLinie);
        inskriptionFjerdeLinie.setBounds(242, 479, 54, 19);

        inskriptionFemteLinie.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        inskriptionFemteLinie.setText("jLabel43");
        add(inskriptionFemteLinie);
        inskriptionFemteLinie.setBounds(242, 499, 54, 19);

        pladsTilLabelNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pladsTilLabelNoChange.setText("Plads til");
        add(pladsTilLabelNoChange);
        pladsTilLabelNoChange.setBounds(10, 531, 39, 14);

        antalNavneLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        add(antalNavneLabel);
        antalNavneLabel.setBounds(60, 530, 19, 14);

        navneLabelNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        navneLabelNoChange.setText("navn(e)");
        add(navneLabelNoChange);
        navneLabelNoChange.setBounds(90, 530, 38, 14);

        skrifttypeLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        skrifttypeLabelNoChange.setText("Skrifttype:");
        add(skrifttypeLabelNoChange);
        skrifttypeLabelNoChange.setBounds(350, 531, 60, 14);

        skriftTypeLabel.setText("jLabel48");
        add(skriftTypeLabel);
        skriftTypeLabel.setBounds(456, 531, 40, 14);

        antalLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        antalLabelNoChange.setText("Antal:                            ");
        antalLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(antalLabelNoChange);
        antalLabelNoChange.setBounds(10, 560, 119, 16);

        vareLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        vareLabelNoChange.setText("Vare:                                                                                                 ");
        vareLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(vareLabelNoChange);
        vareLabelNoChange.setBounds(130, 560, 322, 16);

        prisLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        prisLabelNoChange.setText("Pris:                                  ");
        prisLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(prisLabelNoChange);
        prisLabelNoChange.setBounds(450, 560, 129, 16);

        antaEtLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaEtLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaEtLabel.setPreferredSize(new java.awt.Dimension(115, 16));
        add(antaEtLabel);
        antaEtLabel.setBounds(10, 580, 115, 16);

        antaToLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaToLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaToLabel.setPreferredSize(new java.awt.Dimension(115, 16));
        add(antaToLabel);
        antaToLabel.setBounds(10, 600, 115, 16);

        antaTreLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaTreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaTreLabel.setPreferredSize(new java.awt.Dimension(115, 16));
        add(antaTreLabel);
        antaTreLabel.setBounds(10, 620, 115, 16);

        antaFireLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaFireLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaFireLabel.setPreferredSize(new java.awt.Dimension(115, 16));
        add(antaFireLabel);
        antaFireLabel.setBounds(10, 640, 115, 16);

        antaFemLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaFemLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaFemLabel.setPreferredSize(new java.awt.Dimension(115, 16));
        add(antaFemLabel);
        antaFemLabel.setBounds(10, 660, 115, 16);

        antaSeksLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaSeksLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaSeksLabel.setPreferredSize(new java.awt.Dimension(115, 16));
        add(antaSeksLabel);
        antaSeksLabel.setBounds(10, 680, 115, 16);

        antaSyvLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        antaSyvLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        antaSyvLabel.setPreferredSize(new java.awt.Dimension(115, 16));
        add(antaSyvLabel);
        antaSyvLabel.setBounds(10, 700, 115, 16);

        miljøAfgiftAntalLabelNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        miljøAfgiftAntalLabelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        miljøAfgiftAntalLabelNoChange.setPreferredSize(new java.awt.Dimension(115, 16));
        add(miljøAfgiftAntalLabelNoChange);
        miljøAfgiftAntalLabelNoChange.setBounds(10, 720, 115, 16);

        vareEtLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareEtLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareEtLabel.setPreferredSize(new java.awt.Dimension(319, 16));
        add(vareEtLabel);
        vareEtLabel.setBounds(130, 580, 319, 16);

        vareToLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareToLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareToLabel.setPreferredSize(new java.awt.Dimension(319, 16));
        add(vareToLabel);
        vareToLabel.setBounds(130, 600, 319, 16);

        varetreLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        varetreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        varetreLabel.setPreferredSize(new java.awt.Dimension(319, 16));
        add(varetreLabel);
        varetreLabel.setBounds(130, 620, 319, 16);

        vareFireLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareFireLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareFireLabel.setPreferredSize(new java.awt.Dimension(319, 16));
        add(vareFireLabel);
        vareFireLabel.setBounds(130, 640, 319, 16);

        vareFemLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareFemLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareFemLabel.setPreferredSize(new java.awt.Dimension(319, 16));
        add(vareFemLabel);
        vareFemLabel.setBounds(130, 660, 319, 16);

        vareSeksLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareSeksLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareSeksLabel.setPreferredSize(new java.awt.Dimension(319, 16));
        add(vareSeksLabel);
        vareSeksLabel.setBounds(130, 680, 319, 16);

        vareSyvLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        vareSyvLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vareSyvLabel.setPreferredSize(new java.awt.Dimension(319, 16));
        add(vareSyvLabel);
        vareSyvLabel.setBounds(130, 700, 319, 16);

        miljøAfgiftVareLavbelNoChange.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        miljøAfgiftVareLavbelNoChange.setText("Miljøafgift (2,5%)");
        miljøAfgiftVareLavbelNoChange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        miljøAfgiftVareLavbelNoChange.setPreferredSize(new java.awt.Dimension(319, 16));
        add(miljøAfgiftVareLavbelNoChange);
        miljøAfgiftVareLavbelNoChange.setBounds(130, 720, 319, 16);

        prisEtLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisEtLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisEtLabel.setPreferredSize(new java.awt.Dimension(125, 16));
        add(prisEtLabel);
        prisEtLabel.setBounds(450, 580, 125, 16);

        prisToLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisToLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisToLabel.setPreferredSize(new java.awt.Dimension(125, 16));
        add(prisToLabel);
        prisToLabel.setBounds(450, 600, 125, 16);

        prisTreLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisTreLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisTreLabel.setPreferredSize(new java.awt.Dimension(125, 16));
        add(prisTreLabel);
        prisTreLabel.setBounds(450, 620, 125, 16);

        prisFireLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisFireLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisFireLabel.setPreferredSize(new java.awt.Dimension(125, 16));
        add(prisFireLabel);
        prisFireLabel.setBounds(450, 640, 125, 16);

        prisFemLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisFemLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisFemLabel.setPreferredSize(new java.awt.Dimension(125, 16));
        add(prisFemLabel);
        prisFemLabel.setBounds(450, 660, 125, 16);

        prisSeksLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisSeksLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisSeksLabel.setPreferredSize(new java.awt.Dimension(125, 16));
        add(prisSeksLabel);
        prisSeksLabel.setBounds(450, 680, 125, 16);

        prisSyvLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisSyvLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisSyvLabel.setPreferredSize(new java.awt.Dimension(125, 16));
        add(prisSyvLabel);
        prisSyvLabel.setBounds(450, 700, 125, 16);

        prisMiljøafgift.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        prisMiljøafgift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prisMiljøafgift.setPreferredSize(new java.awt.Dimension(125, 16));
        add(prisMiljøafgift);
        prisMiljøafgift.setBounds(450, 720, 125, 16);

        samletPrisUMomsLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        samletPrisUMomsLabelNoChange.setText("Pris:");
        add(samletPrisUMomsLabelNoChange);
        samletPrisUMomsLabelNoChange.setBounds(401, 740, 30, 14);

        momsLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        momsLabelNoChange.setText("Moms (25%):");
        add(momsLabelNoChange);
        momsLabelNoChange.setBounds(360, 760, 80, 14);

        totalPrisLabelNoChange.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        totalPrisLabelNoChange.setText("Total:");
        add(totalPrisLabelNoChange);
        totalPrisLabelNoChange.setBounds(388, 780, 40, 14);

        samletPrisUMomsLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        samletPrisUMomsLabel.setText("jLabel79");
        add(samletPrisUMomsLabel);
        samletPrisUMomsLabel.setBounds(450, 740, 120, 14);

        momsLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        momsLabel.setText("jLabel80");
        add(momsLabel);
        momsLabel.setBounds(450, 760, 120, 14);

        totalPrisLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        totalPrisLabel.setText("jLabel81");
        add(totalPrisLabel);
        totalPrisLabel.setBounds(450, 780, 120, 14);

        bemærkningerTextArea.setColumns(20);
        bemærkningerTextArea.setRows(5);
        jScrollPane1.setViewportView(bemærkningerTextArea);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 740, 330, 96);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KundeInformationLabelNoChange;
    private javax.swing.JLabel afdelingLabel;
    private javax.swing.JLabel afdelingLabelNoChange;
    private javax.swing.JLabel afhDatoLabel;
    private javax.swing.JLabel afhDatoLabelNoChange;
    private javax.swing.JLabel antaEtLabel;
    private javax.swing.JLabel antaFemLabel;
    private javax.swing.JLabel antaFireLabel;
    private javax.swing.JLabel antaSeksLabel;
    private javax.swing.JLabel antaSyvLabel;
    private javax.swing.JLabel antaToLabel;
    private javax.swing.JLabel antaTreLabel;
    private javax.swing.JLabel antalLabelNoChange;
    private javax.swing.JLabel antalNavneLabel;
    private javax.swing.JTextArea bemærkningerTextArea;
    private javax.swing.JLabel billedeLabel;
    private javax.swing.JLabel datoLabelNoChange;
    private javax.swing.JLabel datoLabelTilOrdrebekræftelse;
    private javax.swing.JLabel infoEtLabel;
    private javax.swing.JLabel infoFemLabel;
    private javax.swing.JLabel infoFireLabel;
    private javax.swing.JLabel infoNiLabel;
    private javax.swing.JLabel infoOtteLabel;
    private javax.swing.JLabel infoSeksLabel;
    private javax.swing.JLabel infoSyvLabel;
    private javax.swing.JLabel infoToLabel;
    private javax.swing.JLabel infoTreLabel;
    private javax.swing.JLabel inskriptionAndenLinie;
    private javax.swing.JLabel inskriptionFemteLinie;
    private javax.swing.JLabel inskriptionFjerdeLinie;
    private javax.swing.JLabel inskriptionFørsteLinie;
    private javax.swing.JLabel inskriptionTredjeLinie;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kirkegaardLabel;
    private javax.swing.JLabel kirkegaardLabelNoChange;
    private javax.swing.JLabel kisteUrneLabel;
    private javax.swing.JLabel kisteUrneLabelNoChange;
    private javax.swing.JLabel kundeAdresseLabel;
    private javax.swing.JLabel kundeNavnLabel;
    private javax.swing.JLabel kundePostOgByLabel;
    private javax.swing.JLabel levDatoLabel;
    private javax.swing.JLabel levDatoLabelNoChange;
    private javax.swing.JLabel miljøAfgiftAntalLabelNoChange;
    private javax.swing.JLabel miljøAfgiftVareLavbelNoChange;
    private javax.swing.JLabel momsLabel;
    private javax.swing.JLabel momsLabelNoChange;
    private javax.swing.JLabel navneLabelNoChange;
    private javax.swing.JLabel nyStenNrLabel;
    private javax.swing.JLabel nyStenNrLabelNoChange;
    private javax.swing.JLabel ordreNrLabelNoChange;
    private javax.swing.JLabel ordreNrLabelTilOrdrebekræftelse;
    private javax.swing.JLabel ordrebekræftelseLabelNoChange;
    private javax.swing.JLabel pladsTilLabelNoChange;
    private javax.swing.JLabel prisEtLabel;
    private javax.swing.JLabel prisFemLabel;
    private javax.swing.JLabel prisFireLabel;
    private javax.swing.JLabel prisLabelNoChange;
    private javax.swing.JLabel prisMiljøafgift;
    private javax.swing.JLabel prisSeksLabel;
    private javax.swing.JLabel prisSyvLabel;
    private javax.swing.JLabel prisToLabel;
    private javax.swing.JLabel prisTreLabel;
    private javax.swing.JLabel raekkeNrLabel;
    private javax.swing.JLabel raekkeOgNrLabelNoChange;
    private javax.swing.JLabel samletPrisUMomsLabel;
    private javax.swing.JLabel samletPrisUMomsLabelNoChange;
    private javax.swing.JLabel skriftTypeLabel;
    private javax.swing.JLabel skrifttypeLabelNoChange;
    private javax.swing.JLabel telefonLabelNoChange;
    private javax.swing.JLabel telefonLabelTilOrdrebekræftelse;
    private javax.swing.JLabel tilfoejelseLabel;
    private javax.swing.JLabel tilfoejelseLabelNoChange;
    private javax.swing.JLabel totalPrisLabel;
    private javax.swing.JLabel totalPrisLabelNoChange;
    private javax.swing.JLabel vareEtLabel;
    private javax.swing.JLabel vareFemLabel;
    private javax.swing.JLabel vareFireLabel;
    private javax.swing.JLabel vareLabelNoChange;
    private javax.swing.JLabel vareSeksLabel;
    private javax.swing.JLabel vareSyvLabel;
    private javax.swing.JLabel vareToLabel;
    private javax.swing.JLabel varetreLabel;
    // End of variables declaration//GEN-END:variables
}
