/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Dimension;
import view.lager.BronzeGUI;
import view.lager.FuglGUI;
import view.lager.GravstenGUI;
import view.lager.PlanGUI;
import view.lager.VaseGUI;

/**
 *
 * @author TheToiletpaper
 */
public class LagerGUI extends javax.swing.JPanel {

    BronzeGUI brg = new BronzeGUI();
    GravstenGUI grg = new GravstenGUI();
    PlanGUI plg = new PlanGUI();
    FuglGUI fug = new FuglGUI();
    VaseGUI vag = new VaseGUI();

    /**
     * Creates new form LagerGUI
     */
    public LagerGUI() {
        
        
        initComponents();
        cardsLager.add(brg);
        cardsLager.add(grg);
        cardsLager.add(plg);
        cardsLager.add(fug);
        cardsLager.add(vag);
        varegruppe.setModel(new javax.swing.DefaultComboBoxModel(new String[]{
                    "Gravsten", "Bronze Dekorationer", "Granitplaner", "Fuglebade", "Granitvaser"
                }));
        ((CardLayout) cardsLager.getLayout()).addLayoutComponent(brg, "Bronze Dekorationer");
        ((CardLayout) cardsLager.getLayout()).addLayoutComponent(grg, "Gravsten");
        ((CardLayout) cardsLager.getLayout()).addLayoutComponent(plg, "Granitplaner");
        ((CardLayout) cardsLager.getLayout()).addLayoutComponent(fug, "Fuglebade");
        ((CardLayout) cardsLager.getLayout()).addLayoutComponent(vag, "Granitvaser");
         skiftLagerPanel("Gravsten");

    }

    public void skiftLagerPanel(String jp) {
        ((CardLayout) cardsLager.getLayout()).show(cardsLager, jp);
    }
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varegruppe = new javax.swing.JComboBox();
        cardsLager = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(100, 100, 100));
        setPreferredSize(new java.awt.Dimension(1280, 480));

        varegruppe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        varegruppe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varegruppeActionPerformed(evt);
            }
        });

        cardsLager.setPreferredSize(new java.awt.Dimension(1280, 480));
        cardsLager.setLayout(new java.awt.CardLayout());

        jButton1.setText("Skift!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardsLager, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addComponent(varegruppe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varegruppe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(cardsLager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void varegruppeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varegruppeActionPerformed
    }//GEN-LAST:event_varegruppeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ((CardLayout) cardsLager.getLayout()).show(cardsLager, (String)varegruppe.getSelectedItem());
       cardsLager.setSize(1280, 480);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardsLager;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox varegruppe;
    // End of variables declaration//GEN-END:variables
}
